name: reviewdog
on: [push]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: '--enable-all --disable=exhaustivestruct,gci,paralleltest,wrapcheck,errorlint'
          reporter: github-check